# Generated by Django 6.1.1 on 2026-09-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheranswer',
            name='language',
            field=models.CharField(db_index=True, default='en-GB', max_length=10),
        ),
    ]
